import requests
#import the keys
import mpesa_keys

headers = {
  'Content-Type': 'application/json',
  'Authorization': 'Bearer Gxxdk0yRZovzyGMDfGm8G6qdVhZC'
}

payload = {
    "BusinessShortCode": mpesa_keys.business_shortCode,
    "Password": "",
    "Timestamp": "", #pwd and timestamp should be generated by self
    "TransactionType": "CustomerPayBillOnline",
    "Amount": 1,
    "PartyA": mpesa_keys.phone_no,
    "PartyB": mpesa_keys.business_shortCode,
    "PhoneNumber": mpesa_keys.phone_no,
    "CallBackURL": "https://mydomain.com/path",
    "AccountReference": "CompanyXLTD",
    "TransactionDesc": "Payment of X" 
  }

response = requests.request("POST", 'https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest', headers = headers, data = payload)
print(response.text.encode('utf8'))