

from urllib import request
import requests
from requests.auth import HTTPBasicAuth
#import the keys
import mpesa_keys
from access_token import generate_access_token
#date and time
from datetime import datetime
#for encoding pwd
import base64

#print(datetime.now())
unformatted_time=datetime.now()
#eliminate dashes n spaces in the timestamp
#strftime--string formatted time
#%Y %m %d %H %M %S
formatted_time=unformatted_time.strftime("%Y%m%d%H%M%S")
    ## ie: 20220824150922
#print(formatted_time,'time now')
#fx to create timestamp

#made up of the business short code(business_shortCode) + stringformattedtime
data_to_encode=mpesa_keys.business_shortCode + mpesa_keys.lipa_na_mpesa_passkey + formatted_time
encoded_password=base64.b64encode(data_to_encode.encode())#we need a bytes-like object, the .encode() encodes it to a utf-8
#print(encoded_string)#output: b'MjAyMjA4MjQxNjE4NTU='..is in binary/bytes  '    '

decoded_password=encoded_password.decode('utf-8')
#print(decoded_password)#output:MjAyMjA4MjQxNjI1NTc=

#generating access-token
the_token=generate_access_token()
print(the_token, "this is a token")

def lipa_na_mpesa():
    access_token=the_token
    api_url='https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest'

    headers = {
    'Authorization': "Bearer %s" % access_token
    }

    payload = {
        "BusinessShortCode": mpesa_keys.business_shortCode,
        "Password": decoded_password,#pwd is base64 encoded *str*
            #https://www.base64decode.org/
            #
        "Timestamp": formatted_time, #timestamp should be generated by self
        "TransactionType": "CustomerPayBillOnline",
        "Amount": 1,
        "PartyA": mpesa_keys.phone_no,
        "PartyB": mpesa_keys.business_shortCode,
        "PhoneNumber": mpesa_keys.phone_no,
        "CallBackURL": "https://fullstackdjango.com/lipanampesa/",
        "AccountReference": "Kangatta LTD",
        "TransactionDesc": "payment of ksh ..." 
    }

    response = requests.request("POST", api_url, headers = headers, json = payload)
    print(response.text.encode('utf8'))

lipa_na_mpesa() #calling fx