

from urllib import request
import requests
from requests.auth import HTTPBasicAuth
#import the keys
import mpesa_keys
from access_token import generate_access_token
from encode import build_pwd
from random_functions import timestamp_conversion
#date and time
from datetime import datetime
#for encoding pwd
import base64

#formatting the date
formatted_time=timestamp_conversion()
#encoding and decoding pwd
decoded_password=build_pwd(formatted_time)

#generating access-token
the_token=generate_access_token()
print(the_token, "this is a token")

def lipa_na_mpesa():
    access_token=the_token
    api_url='https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest'

    headers = {
    'Authorization': "Bearer %s" % access_token
    }

    payload = {
        "BusinessShortCode": mpesa_keys.business_shortCode,
        "Password": decoded_password,#pwd is base64 encoded *str*
            #https://www.base64decode.org/
            #
        "Timestamp": formatted_time, #timestamp should be generated by self
        "TransactionType": "CustomerPayBillOnline",
        "Amount": 1,
        "PartyA": mpesa_keys.phone_no,
        "PartyB": mpesa_keys.business_shortCode,
        "PhoneNumber": mpesa_keys.phone_no,
        "CallBackURL": "https://fullstackdjango.com/lipanampesa/",
        "AccountReference": "Kangatta LTD",
        "TransactionDesc": "payment of ksh ..." 
    }

    response = requests.request("POST", api_url, headers = headers, json = payload)
    print(response.text.encode('utf8'))

lipa_na_mpesa() #calling fx